### ISSUE TITLE
Add a feature to sync at a specific time.

### ISSUE THREAD

**Issue by robinsm** [pbs/pbs-media-manager-craft-plugin#11]
The idea here would be to schedule one or more syncs on a show by show basis so that specific data (not all) could be synced for known timed events that are known well in advance.

An example of this is a show coming out of the PBS passport for a period of 2 weeks where it will be viewable by all during that time.

The video goes on to explain the feature request to sync changes and has been left in for more context.

https://user-images.githubusercontent.com/4096355/234789774-f8211f2c-79d1-4351-a5f4-4c1a26005095.mp4

Full length video [here](https://drive.google.com/drive/u/3/folders/1nuXXTIFETjCVYrPWRBsPlPAZi3F6wxXz)

**Comment by andrewmenich** [comment]
@smaylath this feature has been added to the kenburns media manager plugin repo here https://github.com/pbs/pbs-media-manager-craft-kenburns/commit/4390af3e41659581273e909e1dca3d3b0508f727

It is currently deploying but will update when a preview link is available.

**Comment by smaylath** [comment]
Thank you @andrewmenich noting the project config item Cristina shared here for the next deploy attempt!

Checking for pending migrations ...
Total 2 new Media Manager migrations to be applied:
    - m230705_151024_add_marked_for_deletion_field
    - m230926_143322_add_scheduled_sync_table
*** applying m230705_151024_add_marked_for_deletion_field
Exception: Changes to the project config are not possible while in read-only mode. (/opt/kenburns/vendor/craftcms/cms/src/services/ProjectConfig.php:511)

**Comment by andrewmenich** [comment]
@smaylath I've fixed the error on `develop` and it's ready for review now. https://develop-kenburns.console.pbs.org/admin/mediamanager/scheduler

From this page they can schedule syncs for a date and time. The way this works is that when the site is hit, either from the control panel, front end, or console, the plugin checks if any scheduled tasks are in the past and if so, processes them (begins syncing). The trouble with this is that if they schedule a sync for midnight and nobody is hitting the site, the sync won't start. The better approach would be to have a cron job run every 15 or 30 minutes (whatever interval they need) to hit the site and check for syncs.

**Comment by andrewmenich** [comment]
I reached out to Cristina to see if we could add cron jobs to support this ticket and she said she'd work on it. I provided the following script as what we would want to call in the cron job: `php craft mediamanager/scheduled-sync/index` and that function can be found here: https://github.com/pbs/pbs-media-manager-craft-kenburns/commit/58f1e17ed0c70c1a46e0ca4d0d81c0d5d91029ca

**Comment by SamLaneyPBS** [comment]
I got an "internal server error" when i tried to create a sync schedule item.

**Comment by SamLaneyPBS** [comment]
Hi, I was able to create a sync schedule today. In my test, I tried an episode data update, which worked, and a show update, which did not work. I tried to schedule a sync for the Show Benjamin Franklin, updating the number of episodes. You can see that the number of episodes stayed at 3 (https://develop-kenburns.console.pbs.org/admin/entries/show/212186-benjamin-franklin?site=default#tab--content) 

As of last week, two of the four episodes have been removed (the ones that start with "Spanish Version" in the title). In the show re-sync, It would be expected that:
a) these two episodes no longer show up as green "available" episodes
b) a show sync would update to show 2 episodes as available, or if it syncs to the outdated state, that four episodes are available.

**Comment by smaylath** [comment]
Thank you for testing and providing this note! tagging @andrewmenich to take a look when you have a moment!

**Comment by andrewmenich** [comment]
@SamLaneyPBS Regarding the Bejamin Franklin show sync issues mentioned above - I noticed in the media manager code that the Episode Count is only updated for new shows (AKA when a show is first saved/synced.) Any ideas why that might be the case? I just want to be sure we don't introduce a regression elsewhere if I change that logic. 

Furthermore, the console data for that show indicates the episode count is still `4` so I'm not sure if that's a reliable place to get the episode count, based on the info you shared above. Let me know your thoughts on this!

**Comment by andrewmenich** [comment]
@SamLaneyPBS I meant the media manager data / API

**Comment by SamLaneyPBS** [comment]
OK, I guess there might be a quirk in how we "remove" or unpublish an old episode. I've changed the "availability" for one of the expired episodes to "unavailable" - does that change the number of reported episodes in the API to 3?

**Comment by andrewmenich** [comment]
No, I'm still seeing `episodes_count: 4` under data > attributes > episodes_count

**Comment by SamLaneyPBS** [comment]
OK, now I've actually deleted the record - can you check the API again?

**Comment by andrewmenich** [comment]
Unfortunately I'm still seeing an episode count of 4. Do we know if that number is generated dynamically? If it helps, this is the URL being hit: https://media.services.pbs.org/api/v1/shows/44a78f46-58e6-4d32-844d-853eb62e2476?page=1&platform-slug=bento&platform-slug=partnerplayer

**Comment by SamLaneyPBS** [comment]
Asking our Media Manager team for help - will get back to you!

**Comment by SamLaneyPBS** [comment]
Heya Andrew, here's the response from our Media manager developers:

> That particular api call returns 4 for episode count because that’s how many episode objects exist for the show. It doesn’t and can’t consider the playability of the child assets within the episode objects (too many variables). Knowing if an asset is playable or not (available + published) is managed on the asset level and as I’m sure you know, there are three different types (public, all members, station members).
> We’d recommend the dev explore using this api call instead, which will tell you how many full length episodes belonging to a given show are playable when the call is made:
https://media.services.pbs.org/api/v1/assets/?show-id=44a78f46-58e6-4d32-844d-853eb62e2476&type=full_length&parent-type=episode
> (If you want to know about full lengths in both episodes and specials, you can remove the last param. If you also want to know about all asset types, you can remove the last two params.)
> The season info for each asset is included in the response.

For Ken Burns, we would would want to know about just full length episodes - so we can use that link as-is, I believe.

**Comment by andrewmenich** [comment]
@SamLaneyPBS This should be fixed now. I believe you've run some show syncs while testing issue #10 so let me know if you're seeing the correct episode counts now.

**Comment by SamLaneyPBS** [comment]
I am seeing the correct episode counts now!

**Comment by smaylath** [comment]
deployed to preprod & prod & completed 12.14.23
