### ISSUE TITLE
Add Season and Episode to the API

### ISSUE THREAD

**Issue by smaylath** [pbs/pbs-media-manager-craft-plugin#14]
This exists and the fields exist - it just needs to be added to MM
Below is a screenshot Sam provided as reference from GA

![image002 (8)](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/77697559/54e21b0c-e1fc-4663-b3f0-f21520dc69cd)

**Comment by andrewmenich** [comment]
@smaylath This has been done and pushed to `develop` for preview. I will update with a link once the deploy has completed. https://github.com/pbs/gacraft/commit/694f842c15d31e6e7d732399e7cd5ba16ab5297b

**Comment by SamLaneyPBS** [comment]
This looks good to go!

**Comment by smaylath** [comment]
@andrewmenich this can go to preprod!

**Comment by smaylath** [comment]
deployed to preprod & prod & completed 12.14.23
