### ISSUE TITLE
Provide a mechanism to select which data is synchronised by the media manager.

### ISSUE THREAD

**Issue by robinsm** [pbs/pbs-media-manager-craft-plugin#8]
When using the media manager to sync data down into Craft, some fields are overwritten that have been slightly altered since the last sync.

The below video highlights in particular, iFrame code that has been customised to autoplay as it appears on a page.  Syncing the full show in this instance, overwrites that customisation.

Sometimes, it's relevant to just sync one field.

The following video initially provides some background context to the MM plugin before getting into the issue.

https://user-images.githubusercontent.com/4096355/234782162-63f55e9b-dbdc-453a-b3e9-5a769cfde220.mp4

Full length video [here](https://drive.google.com/drive/u/3/folders/1nuXXTIFETjCVYrPWRBsPlPAZi3F6wxXz)

**Comment by robinsm** [comment]
Notes taken during meeting.

Can we have a more specific synchronize function?
Passport status
Whole thing
Currently have only force regenerate thumbnail

**Comment by andrewmenich** [comment]
@SamLaneyPBS  Just getting back around to this. So the only time a show is synchronized wholesale (i.e Synchronize > Show > Update All Media) is when it's first launched and then if the Passport status changes? Thereafter you're using the Sync Single Media function?

Could you also please remind me how the "Display Passport Icon" value is derived based on the data from the API? 

Thanks!

**Comment by SamLaneyPBS** [comment]
Hi Andrew,

The times a whole show is synchronized is when >1 media asset might be publishing or changing its status. The status can go from "FVOD" (free video on demand), "MVOD" (our membership/subscription service), or "not available" for any streaming rights. This happens for any show, multiple times a year.
After a show initially premieres and all of its video assets are live, it would be great to be able to schedule a "future sync" for that show when we know the content will switch between FVOD and MVOD. So if a show is moving into MVOD on August 30, I could tell Media Manager Plugin to resync that show on that date. Note that 99% of cases all we really want to change is the FVOD to MVOD status, so any sort of sync option that would give more granularity on what is updated - ie, just MVOD status - with a sync customization would be greatly appreciated.

The "display passport icon" is attached to its MVOD state. If "Public Availability" is set to "not available" or a date in the past, and "All Passport Members" is set to a date in the future, it should trigger the "passport icon" to display over the video's thumbnail. Note there is a third rights availability that may get passed through the API called "Your Station's Passport Members" - we can ignore this.

**Comment by andrewmenich** [comment]
@SamLaneyPBS This feature has been put on [KB Develop](https://develop-kenburns.console.pbs.org/admin/mediamanager/synchronize/2) for testing and review. I've attached attached a screenshot for what you can expect. In any of the Synchronization panes ('Synchronize All Shows', 'Synchronize Single Media', show-specific syncs, and 'Synchronize All Shows') you will see a list of checboxes for fields that should be updated on the next sync. 

<img width="1101" alt="image" src="https://github.com/pbs/pbs-media-manager-craft-plugin/assets/29585821/92eb5d8c-928b-4b91-8c71-3473ad07bdc2">

<img width="891" alt="image" src="https://github.com/pbs/pbs-media-manager-craft-plugin/assets/29585821/19130d66-af26-402f-a1e7-e4aedba80817">

**Comment by SamLaneyPBS** [comment]
Hey Andrew,

Using [The Address (full episode)](https://develop-kenburns.console.pbs.org/admin/entries/media/28719-the-address?site=theAddress) and [Learn the Address (clip)](https://develop-kenburns.console.pbs.org/admin/entries/media/28697-learn-the-address?site=theAddress#tab--api) to test the various functions. 

I changed the thumbnail for The Address (full episode) did not update to its original thumbnail after sync

I also tested the Passport Icon, Media Type, Duration, player code, expiration status and Description - those all worked. 

I'm also testing the "sync all shows - passport button", but will leave it running as it looks like that will take quite some time :) 

Would it be possible to add "Title" to the list of resync options? I changed the title of "Learn the Address" to "Learn the Address test" but there's no option to target the title in a new sync.

**Comment by andrewmenich** [comment]
@SamLaneyPBS Thanks for the feedback. It seems like the "force regenerate thumbnail" option was the only thing affecting the Thumbnail field. I have fixed this so that if a thumbnail was changed and the "Thumbnail" option is checked before syncing, then it should update to what comes from the API. 

I also added Title to the list of options. 

Regarding the 'Display Passport Icon?' option - I haven't been able to verify the original logic of the plugin matches the logic you've provided [here](https://github.com/pbs/pbs-media-manager-craft-plugin/issues/10#issuecomment-1791521258) so that might not work as expected yet.

**Comment by SamLaneyPBS** [comment]
Hey Andrew - I believe testing the "sync all shows" with the "display passport icon" setting selected should update the individual video entries, seen here:

![image](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/129447081/24f33d3a-2d51-41de-9f74-9d9e5792c699)

The Passport logic is more straightforward for "videos" than it is for "shows". For Shows, we [need this logic](https://github.com/pbs/pbs-media-manager-craft-plugin/issues/10#issuecomment-1791521258), for Videos - including any video that has the toggle "display passport icon", it's a more straightforward check of is the video not available in the "public" date field, and is the video available to "All Passport Members". 

I'm running the "all shows sync - update 'display passport icon'" test again this morning - I'll let you know the results.

**Comment by SamLaneyPBS** [comment]
Update: "all shows sync - update 'display passport icon'" is working just fine. 

There seems to be a issue where assets that should be marked for deletion don't get marked as such after a sync. For example, the asset ["En Español: This Is What We Do (July 1967-December 1967)"](https://develop-kenburns.console.pbs.org/admin/entries/media/208504-en-espa%C3%B1ol-this-is-what-we-do-july-1967-december-1967?site=theVietnamWar) doesn't show an updated "last synced" value (which makes sense, the asset doesn't exist in Media manager any more), but it's not getting flagged for deletion either.

**Comment by andrewmenich** [comment]
This logic has been added in [KB v3.3.3](https://github.com/pbs/pbs-media-manager-craft-kenburns/releases/tag/v3.3.3) and is on the KB Develop site for review.

**Comment by SamLaneyPBS** [comment]
This is looking perfect!

**Comment by smaylath** [comment]
deployed to preprod & prod & completed 12.14.23
